#include QMK_KEYBOARD_H

#define _BASE 0
#define _FN1 1
#define _FN2 2
#define _FN3 3
#define _FN4 4

#define XXXXXXX KC_NO
#define _______ KC_TRNS

#define KC_MS_U KC_MS_UP
#define KC_MS_D KC_MS_DOWN
#define KC_MS_L KC_MS_LEFT
#define KC_MS_R KC_MS_RIGHT
#define KC_BTN1 KC_MS_BTN1
#define KC_BTN2 KC_MS_BTN2
#define KC_PWR KC_SYSTEM_POWER
#define PREVENT_STUCK_MODIFIERS

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [_BASE] = LAYOUT(
    KC_GESC,   KC_Q,     KC_W,     KC_E,     KC_R,     KC_T,     KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,     KC_MINS,   KC_BSPC,
    KC_TAB,   KC_A,     KC_S,     KC_D,     KC_F,     KC_G,     KC_H,     KC_J,     KC_K,     KC_L,     KC_SCLN,  KC_ENT,
    KC_LSFT,  KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,     KC_N,     KC_M,     KC_COMM,  KC_DOT,   KC_QUOT,  RSFT_T(KC_DEL),
    KC_LCTL,  MO(3),  KC_LALT, XXXXXXX, XXXXXXX,  KC_SPC, XXXXXXX,     KC_SLSH,   MO(2),   TG(1)
  ),

  [_FN1] = LAYOUT(
    KC_GRV,   KC_1,     KC_2,     KC_3,     KC_4,     KC_5,     KC_6,     KC_7,     KC_8,     KC_9,     KC_0,     KC_MINS,  KC_DEL,
    KC_CALC,    XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_4,     KC_5,     KC_6,     KC_PPLS,  KC_ENT,
    KC_LSFT,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_1,     KC_2,     KC_3,     KC_COMM,    KC_RSFT,
    KC_LCTL,  KC_EQL,  KC_LALT, XXXXXXX, XXXXXXX, KC_0, XXXXXXX, KC_PDOT,  XXXXXXX,   _______
  ),

  [_FN2] = LAYOUT(
    KC_TILD,  KC_EXLM,  KC_AT,    KC_HASH,  KC_DLR,   KC_PERC,  KC_CIRC,  KC_AMPR,  KC_ASTR,  KC_LPRN,  KC_RPRN,  XXXXXXX,  XXXXXXX,
    LALT(LCTL(KC_ESC)),  XXXXXXX,  XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,  KC_HOME,  KC_PGDN,  KC_PGUP,  KC_END,  XXXXXXX,  KC_INS,
    KC_LSFT,  XXXXXXX,  XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,  KC_LBRC,  KC_RBRC,  XXXXXXX,  KC_RSFT,
    KC_LCTL,  KC_LGUI,  KC_LALT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  KC_BSLS,  KC_TRNS,  KC_PSCR
  ),

  [_FN3] = LAYOUT(
    RESET,  KC_F1,  KC_F2,    KC_F3,  KC_F4,   KC_F5,  KC_F6,  KC_F7,  KC_F8,  KC_F9,  KC_F10,  KC_F11,  KC_F12,
    MO(4),  XXXXXXX,  XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,  KC_LEFT,  KC_DOWN,  KC_UP,  KC_RGHT,  XXXXXXX,  LALT(LCTL(KC_T)),
    XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,  KC_VOLU,  KC_VOLD,  XXXXXXX,  KC_RSFT,
    KC_LCTL,  KC_TRNS,  KC_LALT, XXXXXXX, XXXXXXX,  KC_BSPC,  XXXXXXX, XXXXXXX,  XXXXXXX,  XXXXXXX
  ),

  [_FN4] = LAYOUT(
    XXXXXXX,  XXXXXXX,  XXXXXXX,    XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,
    KC_TRNS,  XXXXXXX,  XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,  KC_MS_L,  KC_MS_D,  KC_MS_U,  KC_MS_R,  XXXXXXX,  KC_PWR,
    XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,
    XXXXXXX,  XXXXXXX,  KC_BTN2, XXXXXXX, XXXXXXX,  KC_BTN1,  XXXXXXX, XXXXXXX,  XXXXXXX,  XXXXXXX
  ),


};
